W=~/Work
NI=~/Work/Nimbella
NC=~/Work/Neuronix
SC=~/Work/SciabarraCom
COSH=~/Dropbox/Work/Common/Share
OWRG=~/go/src/github.com/apache/incubator-openwhisk-runtime-go
OWRA=~/go/src/github.com/apache/incubator-openwhisk-runtime-actionloop
OWDT=~/go/src/github.com/apache/incubator-openwhisk-devtools
OWDK=~/go/src/github.com/apache/incubator-openwhisk-deploy-kube
CODE="/Users/michelesciabarra/Library/Application Support/Code/User"
NIM=~/Work/Nimbella/main
HCK="/Users/msciab/Work/Hack"
NDM="/Users/msciab/Work/Butterfly/nimbella-crud-demo"
FAW="/Users/msciab/Work/Butterfly/faaswars"
NIB="/Users/msciab/Work/Nimbella/nimbuilder"
NAW="/Users/msciab/Work/SciabarraCom/neroni-aws/aws"
OB="/Users/msciab/Work/openwhisk-blog"
