PA=~/Work/DevOps/parthenon
BK=~/Work/Book
SH=~/Dropbox/Work/Common/Share
HA=~/Work/Hack
OW=~/Work/go/src/github.com/apache
DO=~/Work/DevOps
OWRG=~/go/src/github.com/apache/incubator-openwhisk-runtime-go
OWRA=~/go/src/github.com/apache/incubator-openwhisk-runtime-actionloop
OWDT=~/go/src/github.com/apache/incubator-openwhisk-devtools
OWDK=~/go/src/github.com/apache/incubator-openwhisk-deploy-kube
CODE="/Users/michelesciabarra/Library/Application Support/Code/User"
TLAS=~/Work/Telmore/2016/agilesites-telmore-ng
TLMI=~/Work/Telmore/2018/oldcms-migrator/vagrant
DOPA="~/Work/DevOps/parthenon/ansible"
LO11="~/Work/Book/learning-openwhisk/Chapter11"
LO08="~/Work/Book/learning-openwhisk/Chapter8"
