PA=~/Work/DevOps/parthenon
BK=~/Work/Book
SH=~/Dropbox/Work/Common/Share
TLAS=~/Work/Telmore/2016/agilesites-telmore-ng
TLMI=~/Work/Telmore/2018/oldcms-migrator/vagrant
OW=~/Work/go/src/github.com/apache
OWRG=~/go/src/github.com/apache/incubator-openwhisk-runtime-go
OWDT=~/go/src/github.com/apache/incubator-openwhisk-devtools
OWDK=~/go/src/github.com/apache/incubator-openwhisk-deploy-kube
CODE="/Users/michelesciabarra/Library/Application Support/Code/User"
DO=/Users/michelesciabarra/Work/DevOps
DOPA="/Users/michelesciabarra/Work/DevOps/parthenon/ansible"
LO11="/Users/michelesciabarra/Work/Book/learning-openwhisk/Chapter11"
LO08="/Users/michelesciabarra/Work/Book/learning-openwhisk/Chapter8"
